language: python
install:
  - pip install -r reqs.txt
  - pip install -U pytest
  - pip install .
  - pip install codecov
script:
  - python -m pytest --cov=tmux_session_utils tmux_session_utils/tests
after_success:
  - codecov
